
name: Release Artifacts in Azure

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Release Channel'
        required: true
        default: 'internal'
        type: choice
        options:
          - prod
          - beta
          - internal
      publicationdirectory:
        description: 'Publication Directory'
        required: true
        default: 'dist'
        type: choice
        options:
          - dist
          - dist-certmaster
  workflow_call:
    inputs:
      channel:
        description: 'Release Channel'
        required: true
        type: string
      publicationdirectory:
        description: 'Publication Directory'
        required: true
        type: string
# environment secrets are not available if not passed explicitly: https://github.com/actions/runner/issues/1490
      secrets:
        AZURE_CLIENT_ID:
          required: true
        AZURE_TENANT_ID:
          required: true

permissions:
      id-token: write
      contents: read

jobs:
  release-in-azure:
    environment: AzureC4A8
    runs-on: ubuntu-latest
    steps:
      - name: Find file name of Artifact to Publish
        uses: kanga333/variable-mapper@master
        with:
          key: "${{ inputs.publicationdirectory }}-${{ inputs.channel }}"
          map: |
            {
              "dist-prod": {
                "publicationfile": "Artifacts.zip"
              },
              "dist-beta": {
                "publicationfile": "Artifacts-Beta.zip"
              },
              "dist-intern(al)?": {
                "publicationfile": "Artifacts-Intern.zip"
              },
              "dist-certmaster-prod": {
                "publicationfile": "CertMaster-Artifacts.zip"
              },
              "dist-certmaster-beta": {
                "publicationfile": "CertMaster-Artifacts-Beta.zip"
              },
              "dist-certmaster-intern(al)?": {
                "publicationfile": "CertMaster-Artifacts-Intern.zip"
              }
            }

      - name: Print what we have found so far (Debug)
        run: |
          echo "Selected directory ${{ inputs.publicationdirectory }} in channel ${{ inputs.channel }}"
          echo "File to publish is ${{ env.publicationfile }}"

      - name: Check Input
        if: ${{ env.publicationfile == '' }}
        run: exit 1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in with Azure
        uses: bb-froggy/login@error-message-on-throw
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Copy file to Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload --auth-mode login --overwrite -f ${{ inputs.publicationdirectory }}/${{ env.publicationfile }} --account-name scepmanartifactsinstall --container-name ${{ inputs.publicationdirectory }} --name ${{ env.publicationfile }}