
name: Release Artifacts in Azure

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Release Channel'
        required: true
        default: 'internal'
        type: choice
        options:
          - production
          - beta
          - internal
      publicationdirectory:
        description: 'Publication Directory'
        required: true
        default: 'dist'
        type: choice
        options:
          - dist
          - dist-certmaster

permissions:
      id-token: write
      contents: read

jobs:
  release-in-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Find file name of Artifact to Publish
        uses: kanga333/variable-mapper@master
        with:
          key: "${{ inputs.publicationdirectory }}-${{ inputs.channel }}"
          map: |
            {
              "dist-production": {
                "publicationfile": "Artifacts.zip"
              },
              "dist-beta": {
                "publicationfile": "Artifacts-Beta.zip"
              },
              "dist-internal": {
                "publicationfile": "Artifacts-Intern.zip"
              },
              "dist-certmaster-production": {
                "publicationfile": "CertMaster-Artifacts.zip"
              },
              "dist-certmaster-beta": {
                "publicationfile": "CertMaster-Artifacts-Beta.zip"
              },
              "dist-certmaster-internal": {
                "publicationfile": "CertMaster-Artifacts-Intern.zip"
              }
            }

      - name: Print what we have found so far (Debug)
        run: |
          echo "Selected directory ${{ inputs.publicationdirectory }} in channel ${{ inputs.channel }}"
          echo "File to publish is ${{ env.publicationfile }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in with Azure
        uses: bb-froggy/login@error-message-on-throw
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          #subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          allow-no-subscriptions: true

      - name: Copy file to Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage upload -f ${{ inputs.publicationdirectory }}/${{ env.publicationfile }} --account-name scepmanartifactsinstall --container-name ${{ inputs.publicationdirectory }} --blob-name ${{ env.publicationfile }}